import React, { useState, useEffect } from 'react';
import { Dialog, Button, TextField } from '../components';
import { nanoid } from '../nanoid';
type Profile = { id: string; name: string; host: string; port: number; username: string; auth: { type: 'password'; password: string } | { type: 'privateKey'; privateKey: string; passphrase?: string } };
type P = { open: boolean; onClose: () => void; existing?: Profile | null; onSaved: () => void };
const empty: Profile = { id: '', name: '', host: '', port: 22, username: '', auth: { type: 'password', password: '' } };
export default function ProfileDialog({ open, onClose, existing, onSaved }: P) {
  const [f, setF] = useState<Profile>({ ...empty, id: nanoid() }); const [at, setAt] = useState<'password' | 'privateKey'>('password');
  const [pw, setPw] = useState(''); const [pk, setPk] = useState(''); const [pp, setPp] = useState('');
  const [saving, setSaving] = useState(false); const [err, setErr] = useState('');
  useEffect(() => { if (open) { if (existing) { setF(existing); setAt(existing.auth.type); if (existing.auth.type === 'password') { setPw(existing.auth.password); setPk(''); setPp(''); } else { setPw(''); setPk(existing.auth.privateKey); setPp(existing.auth.passphrase ?? ''); } } else { setF({ ...empty, id: nanoid() }); setAt('password'); setPw(''); setPk(''); setPp(''); } setErr(''); setSaving(false); } }, [open, existing]);
  const up = (k: keyof Profile, v: any) => setF(x => ({ ...x, [k]: v }));
  async function save() { if (!f.name.trim() || !f.host.trim() || !f.username.trim()) { setErr('Name, host, and username required.'); return; } setSaving(true); setErr(''); try { const auth = at === 'password' ? { type: 'password' as const, password: pw } : { type: 'privateKey' as const, privateKey: pk, passphrase: pp || undefined }; await window.sshWorkbench.profiles.upsert({ ...f, port: Number(f.port) || 22, auth }); onSaved(); onClose(); } catch (e: any) { setErr(String(e?.message ?? e)); } finally { setSaving(false); } }
  return (<Dialog open={open} onClose={onClose} title={existing ? 'Edit Profile' : 'New Profile'} description="SSH connection details." footer={<><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="primary" onClick={save} disabled={saving}>{saving ? 'Saving...' : 'Save'}</Button></>}>
    <div className="col gap-md"><TextField label="Name" placeholder="My Server" value={f.name} onChange={v => up('name', v)} autoFocus /><div className="row gap-md"><div className="grow"><TextField label="Host" placeholder="192.168.1.10" value={f.host} onChange={v => up('host', v)} /></div><div style={{ width: 100 }}><TextField label="Port" type="number" placeholder="22" value={String(f.port)} onChange={v => up('port', v)} /></div></div><TextField label="Username" placeholder="admin" value={f.username} onChange={v => up('username', v)} /><div className="field"><label className="field-label">Auth</label><div className="radio-group"><label className={`radio-option ${at === 'password' ? 'active' : ''}`}><input type="radio" name="at" checked={at === 'password'} onChange={() => setAt('password')} />Password</label><label className={`radio-option ${at === 'privateKey' ? 'active' : ''}`}><input type="radio" name="at" checked={at === 'privateKey'} onChange={() => setAt('privateKey')} />Key</label></div></div>{at === 'password' && <TextField label="Password" type="password" value={pw} onChange={setPw} />}{at === 'privateKey' && <><TextField label="Private Key" textarea value={pk} onChange={setPk} placeholder="Paste PEM/OpenSSH key" /><TextField label="Passphrase" type="password" value={pp} onChange={setPp} placeholder="Optional" /></>}{err && <div style={{ color: 'var(--danger)', fontSize: 'var(--fs-sm)' }}>{err}</div>}</div></Dialog>);
}
