import React, { useState, useEffect } from 'react';
import { Dialog, Button, TextField } from '../components';
type ST = 'rdp' | 'web' | 'database' | 'custom'; type P = { open: boolean; onClose: () => void; profileId: string; onCreated: () => void };
const svcs: { type: ST; icon: string; title: string; desc: string }[] = [{ type: 'rdp', icon: '🖥️', title: 'Secure RDP', desc: 'RDP via SSH.' }, { type: 'web', icon: '🌐', title: 'Secure Web', desc: 'Private web app.' }, { type: 'database', icon: '🗄️', title: 'Secure Database', desc: 'PostgreSQL/MySQL/MSSQL.' }, { type: 'custom', icon: '🔧', title: 'Custom Tunnel', desc: 'Any host:port.' }];
const dbP = [{ l: 'PostgreSQL (5432)', p: 5432 }, { l: 'MySQL (3306)', p: 3306 }, { l: 'MSSQL (1433)', p: 1433 }, { l: 'Custom', p: 0 }];
export default function ServiceWizard({ open, onClose, profileId, onCreated }: P) {
  const [step, setStep] = useState(0); const [svc, setSvc] = useState<ST>('rdp'); const [host, setHost] = useState(''); const [port, setPort] = useState(''); const [name, setName] = useState(''); const [ob, setOb] = useState(true); const [di, setDi] = useState(0); const [ld, setLd] = useState(false); const [err, setErr] = useState('');
  useEffect(() => { if (open) { setStep(0); setSvc('rdp'); setHost(''); setPort(''); setName(''); setOb(true); setDi(0); setLd(false); setErr(''); } }, [open]);
  function ep() { if (svc === 'rdp') return 3389; if (svc === 'database' && dbP[di].p > 0) return dbP[di].p; return Number(port) || 80; }
  async function go() { if (!host.trim()) { setErr('Host required.'); return; } setLd(true); setErr(''); try { if (svc === 'rdp') await window.sshWorkbench.services.openRdp(profileId, host); else if (svc === 'web') await window.sshWorkbench.services.openWeb(profileId, host, ep(), ob); else await window.sshWorkbench.tunnels.create(profileId, { kind: 'local', name: name || `${svc === 'database' ? 'DB' : 'Tunnel'} -> ${host}:${ep()}`, remoteHost: host, remotePort: ep(), bindHost: '127.0.0.1', disposable: true, idleTimeoutMs: 7200000 }); onCreated(); onClose(); } catch (e: any) { setErr(String(e?.message ?? e)); } finally { setLd(false); } }
  return (<Dialog open={open} onClose={onClose} title="Launch Secure Service" description={['Choose service.', 'Target details.', 'Confirm.'][step]} footer={<>{step > 0 && <Button variant="ghost" onClick={() => setStep(step - 1)}>Back</Button>}<div style={{ flex: 1 }} /><Button variant="ghost" onClick={onClose}>Cancel</Button>{step < 2 ? <Button variant="primary" onClick={() => setStep(step + 1)} disabled={step === 1 && !host.trim()}>Next</Button> : <Button variant="primary" onClick={go} disabled={ld}>{ld ? 'Launching...' : 'Launch'}</Button>}</>}>
    <div className="wizard-steps"><div className={`wizard-step ${step > 0 ? 'done' : step === 0 ? 'active' : ''}`} /><div className={`wizard-step ${step > 1 ? 'done' : step === 1 ? 'active' : ''}`} /><div className={`wizard-step ${step === 2 ? 'active' : ''}`} /></div>
    {step === 0 && <div className="col gap-md">{svcs.map(s => <div key={s.type} onClick={() => setSvc(s.type)} style={{ display: 'flex', gap: 'var(--sp-md)', alignItems: 'center', padding: 'var(--sp-md)', borderRadius: 'var(--r-md)', border: `1px solid ${svc === s.type ? 'var(--accent)' : 'var(--border)'}`, background: svc === s.type ? 'rgba(108,99,255,0.08)' : 'transparent', cursor: 'pointer' }}><div style={{ fontSize: 28 }}>{s.icon}</div><div><div className="text-bold">{s.title}</div><div className="text-sm text-secondary">{s.desc}</div></div></div>)}</div>}
    {step === 1 && <div className="col gap-md"><TextField label={svc === 'rdp' ? 'Windows Host' : 'Target Host'} placeholder="10.0.1.50" value={host} onChange={setHost} autoFocus />{svc === 'web' && <><TextField label="Port" type="number" placeholder="80" value={port} onChange={setPort} /><label className="row text-sm" style={{ cursor: 'pointer' }}><input type="checkbox" checked={ob} onChange={e => setOb(e.target.checked)} />Open in browser</label></>}{svc === 'database' && <div className="field"><label className="field-label">Type</label><div className="radio-group" style={{ flexWrap: 'wrap' }}>{dbP.map((pr, i) => <label key={i} className={`radio-option ${di === i ? 'active' : ''}`}><input type="radio" name="db" checked={di === i} onChange={() => { setDi(i); if (pr.p > 0) setPort(String(pr.p)); }} />{pr.l}</label>)}</div>{dbP[di].p === 0 && <TextField label="Port" type="number" value={port} onChange={setPort} />}</div>}{svc === 'custom' && <><TextField label="Remote Port" type="number" placeholder="8080" value={port} onChange={setPort} /><TextField label="Name" placeholder="Internal API" value={name} onChange={setName} /></>}</div>}
    {step === 2 && <div className="col gap-md"><div className="card" style={{ background: 'var(--bg-deep)' }}><div className="text-bold">{svcs.find(s => s.type === svc)?.icon} {svcs.find(s => s.type === svc)?.title}</div><div className="tunnel-route">127.0.0.1:(auto) -&gt; {host || '?'}:{ep()}</div></div><div className="explain-panel open"><div className="explain-panel-inner">Encrypted SSH tunnel. No ports exposed. Auto-closes on disconnect.</div></div>{err && <div style={{ color: 'var(--danger)', fontSize: 'var(--fs-sm)' }}>{err}</div>}</div>}</Dialog>);
}
